# Generated by Django 5.0.14 on 2026-07-23 19:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Leave empty to use the service default duration.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the service default price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='services.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['staff', 'service'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'service'), name='unique_staff_service'),
        ),
    ]
