# Generated by Django 5.0.14 on 2026-07-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffservice_staffservice_unique_staff_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('operator', 'Operator'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20),
        ),
    ]
