# Generated by Django 5.0.14 on 2026-07-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_serviceline_servicecategory_and_more'),
        ('staff', '0003_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='services.servicevariant'),
        ),
    ]
