# Generated by Django 5.0.14 on 2026-07-26 18:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('services', '0002_remove_service_duration_minutes_remove_service_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceLine',
            new_name='ServiceCategory',
        ),
        migrations.RemoveField(
            model_name='service',
            name='line',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Default duration in minutes.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default service price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterModelTable(
            name='servicecategory',
            table='services_serviceline',
        ),
    ]
