# Generated by Django 5.0.14 on 2026-08-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_room_equipment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevariant',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Extra time required after service.'),
        ),
    ]
