# Generated by Django 5.0.14 on 2026-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_notes_alter_appointment_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('admin_panel', 'Admin Panel'), ('telegram', 'Telegram'), ('website', 'Website')], default='admin_panel', max_length=20),
        ),
    ]
