# Generated by Django 5.0.14 on 2026-08-04 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('recipient_type', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In App')], default='in_app', max_length=20)),
                ('approval_required', models.BooleanField(default=False)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic')),
            ],
            options={
                'ordering': ['event_type'],
                'indexes': [models.Index(fields=['clinic', 'event_type'], name='notificatio_clinic__ecce4a_idx'), models.Index(fields=['event_type', 'is_active'], name='notificatio_event_t_cce880_idx')],
            },
        ),
    ]
