# Generated by Django 5.0.14 on 2026-08-04 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('notifications', '0002_notificationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In App')], default='in_app', max_length=20)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic')),
            ],
            options={
                'ordering': ['event_type', 'channel'],
                'indexes': [models.Index(fields=['clinic', 'event_type'], name='notificatio_clinic__586314_idx'), models.Index(fields=['event_type', 'channel'], name='notificatio_event_t_d33346_idx')],
            },
        ),
    ]
